name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
  - cron: '0 0 15 * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  main:
    name: main ci
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-22.04, rust: stable}
          - {os: windows-latest, rust: stable-msvc}
          - {os: windows-latest, rust: stable-gnu}
          - {os: macos-latest, rust: stable}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Rust (${{matrix.rust}})
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: '${{matrix.rust}}'
      - name: Build and test (no features)
        run: cargo test
      - name: Build and test (zstd)
        run: cargo test --features zstd
      - name: Build and test (bindgen, zstd)
        run: cargo test --features bindgen,zstd
      - name: Build and test (simd enabled)
        env:
          RUSTFLAGS: "-C target-feature=+sse2,+avx2"
        run: cargo test --features bindgen,zstd
